# Generated by Django 3.0.5 on 2020-04-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successStories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='successstories',
            name='description',
        ),
    ]
