# Generated by Django 3.0.5 on 2020-04-19 21:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successStories', '0002_remove_successstories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
