# Generated by Django 3.0.5 on 2020-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
