# Generated by Django 3.0.5 on 2020-05-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chateasd',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
