# Generated by Django 3.0.5 on 2020-05-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_chateasd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chateasd',
        ),
    ]
