# Generated by Django 3.0.5 on 2020-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_auto_20200418_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpost',
            name='careerFile',
            field=models.ImageField(null=True, upload_to='Career(Job/Internship)'),
        ),
    ]
