# Generated by Django 3.0.5 on 2020-04-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_auto_20200418_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpost',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='Career(jobs-intership)'),
        ),
        migrations.AlterField(
            model_name='careerpost',
            name='careerFile',
            field=models.ImageField(null=True, upload_to='Career(jobs-intership)'),
        ),
    ]
