# Generated by Django 3.0.5 on 2020-04-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20200418_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpost',
            name='imageFile',
        ),
    ]
