# Generated by Django 3.0.5 on 2020-04-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_remove_careerpost_imagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpost',
            old_name='careerFile',
            new_name='image',
        ),
    ]
