# Generated by Django 3.0.5 on 2020-04-19 15:44

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_auto_20200419_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpost',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
