# Generated by Django 3.0.5 on 2020-04-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_auto_20200419_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpost',
            name='description',
            field=models.TextField(),
        ),
    ]
