# Generated by Django 3.0.7 on 2020-07-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
