# Generated by Django 3.0.7 on 2020-07-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0003_auto_20200707_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
