# Generated by Django 3.0.7 on 2020-07-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0005_workexperience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDegree',
        ),
    ]
