# Generated by Django 3.0.7 on 2020-07-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0007_userdegree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDegree',
        ),
    ]
