# Generated by Django 3.0.7 on 2020-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0009_userdegree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alumniType',
            field=models.CharField(choices=[('Student Alumni', 'Student Alumni'), ('Professional Alumni', 'Professional Alumni')], max_length=30),
        ),
    ]
