# Generated by Django 3.0.7 on 2020-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0012_auto_20200709_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(null=True, upload_to='Profile (User)'),
        ),
    ]
