# Generated by Django 3.0.7 on 2020-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0013_auto_20200710_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdegree',
            name='dateFinished',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdegree',
            name='dateStarted',
            field=models.CharField(max_length=15),
        ),
    ]
