# Generated by Django 3.0.7 on 2020-07-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0014_auto_20200712_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdegree',
            name='dateFinished',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdegree',
            name='dateStarted',
            field=models.IntegerField(),
        ),
    ]
