# Generated by Django 3.0.7 on 2020-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0015_auto_20200712_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='images/user-logo.jpg', null=True, upload_to='Profile (User)'),
        ),
    ]
