# Generated by Django 3.0.7 on 2020-08-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileDashboard', '0016_auto_20200809_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='Profile (User)/user-logo.jpg', null=True, upload_to='Profile (User)'),
        ),
    ]
